import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App for testing',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="flex h-8 justify-center bg-black gap-5 p-16">
					<Link className="font-medium text-white dark:text-blue-500 hover:underline" href="/">
						Home
					</Link>
					<Link
						className="font-medium text-white dark:text-blue-500 hover:underline"
						href="/dashboard"
					>
						Dashboard
					</Link>
				</nav>
				{children}
			</body>
		</html>
	);
}
